spring:
  datasource:
    url: jdbc:h2:D:\35SCJ\Spring\batch\fiapcervejariabatch2;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: D:\35SCJ\Spring\batch\FilesToDelete\text2.txt
  input: classpath:arquivo-bd.txt